logging:
  level: 'info'
  file: 'prices.log'

blockchain: 'bsc'
token_adress: '0xc748673057861a797275CD8A068AbB95A902e8de'
check_interval: 20

output:
  format: 'es'

#output:
#  format: 'csv'
#  path: '/home/yims'
