logging:
  level: 'debug'
  file: 'scrapping.log'

blockchain: 'bsc'
token_adress: '0xc748673057861a797275CD8A068AbB95A902e8de'

#blockchain: 'eth'
#token_adress: '0xB8c77482e45F1F44dE1745F52C74426C631bDD52'

# output format (es, csv)
output:
  format: 'es'

#output:
#  format: 'csv'
#  path: '/home/yims'

# Get history of trades (history=True) or get new trades (history=False)
history: False
# Don't get price from bogged while getting bsc trades
disable_price_check: True

# Filters to apply before saving trades (ex: get only trades with num_tokens > 100)
filter:
  num_tokens: 0