logging:
  level: 'debug'
  file: 'scrapping.log'

#blockchain: 'bsc'
#token_adress: '0xc748673057861a797275CD8A068AbB95A902e8de'

blockchain: 'eth'
token_adress: '0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE'

# Get history of trades (history=True) or get new trades (history=False)
history: False

# Filters to apply before saving trades (ex: get only trades with num_tokens > 100)
filter:
  num_tokens: 1000