window.isBackButton=false;window.isFrTxns=false;window.isFrHold=false;window.isFrReadC=false;window.isFrWriteC=false;window.isFrInventory=false;window.isFrDexTracker=false;window.isFrTokenAnayltics=false;window.token_holders_loaded=false;window.token_transactions_loaded=false;window.tokenChartLoaded=false;window.writeContractLoaded=false;window.readContractLoaded=false;window.token_inventory_loaded=false;window.dexTrackerLoaded=false;window.token_analytics_loaded=false;window.readProxyContractLoaded=false;window.writeProxyContractLoaded=false;function openModal(){$('#WalletModal').modal('show');}
function closeModal(){$('#WalletModal').modal('hide');}
function openProxyModal(){$('#WalletModalProxyIframe').modal('show');}
function closeProxyModal(){$('#WalletModalProxyIframe').modal('hide');}
if(!!window.performance&&window.performance.navigation.type===2){window.isFrTxns=true;window.isFrHold=true;window.isFrChart=true;window.isFrReadC=true;window.isFrWriteC=true;window.isFrInventory=false;window.isBackButton=true;window.isFrDexTracker=true;window.isFrTokenAnayltics=true;};$(document).ready(function(){$("[data-toggle-second='tooltip']").tooltip({trigger:'hover'});$.HSCore.components.HSClipboard.init('.js-clipboard');$("#hdnTokenTxns2").val(strGlobal);if(hash!=''){if(hash.indexOf('images-')!==-1){hash='inventory';updatehash(hash);activaTab(hash);}else{activaTab(hash);}}else{loadIframeSource3();}
$('#darkModaBtn').on('click',function(){if($('body').hasClass('dark-mode')){$('#cmc_logo').attr('src','/images/cmc_dark.svg?v=0.01');$('#uniswap_logo').attr('src','/images/uni_dark.svg?v=0.01');$('#coingecko_logo').attr('src','/images/coingecko-darkmode.svg?v=0.01');}else{$('#cmc_logo').attr('src','/images/cmc.svg?v=0.01');$('#uniswap_logo').attr('src','/images/uni.svg?v=0.02');$('#coingecko_logo').attr('src','/images/coingecko.svg?v=0.01');}});});function activaTab(tab){var subtab='0';if(tab.indexOf('comment')>=0){tab='comments';loaddisqus();window.parent.document.getElementById('overlayMain').style.display='none';}else if(tab.indexOf('balances')>=0){loadIframeSource2();}else if(tab.indexOf('inventory')>=0){loadIframeSource6();}else if(tab.indexOf('tokenTrade')>=0&&enableTokenTrades){loadIframeSource7();window.parent.document.getElementById('overlayMain').style.display='none';}else if(tab.indexOf('tokenAnalytics')>=0&&enableTokenAnalytic){loadIframeSource8();window.parent.document.getElementById('overlayMain').style.display='none';}else if(tab.indexOf('readContract')>=0){subtab='1';loadIframeSource();}else if(tab.indexOf('writeContract')>=0){subtab='1';loadIframeSource5();}else if(tab.indexOf('readProxyContract')>=0){subtab='1';loadIframeSourceProxyRead();}else if(tab.indexOf('writeProxyContract')>=0){subtab='1';loadIframeSourceProxyWrite();}else if(tab.indexOf('tokenInfo')>=0){window.parent.document.getElementById('overlayMain').style.display='none';}else{hash='';updatehash(hash);loadIframeSource3();window.parent.document.getElementById('overlayMain').style.display='none';};var obj2=document.getElementById('ContentPlaceHolder1_li_writeContract');var obj3=document.getElementById('ContentPlaceHolder1_li_readProxyContract');var obj4=document.getElementById('ContentPlaceHolder1_li_writeProxyContract');if(subtab==='0'){$('.nav_tabs1 a[href="#'+tab+'"]').tab('show');if(obj2===null&&obj3===null&&obj4===null){document.getElementById('nav_subtabs').style.display="none";$("#readContract").attr("style","display:visible;");}else{document.getElementById('nav_subtabs').style.display="visible";$("#readContract").attr("style","display:visible;");$("#writeContract").attr("style","display:none;");$("#readProxyContract").attr("style","display:none;");$("#writeProxyContract").attr("style","display:none;");}}else if(subtab=='1'){$('.nav_tabs1 a[href="#contracts"]').tab('show');if(obj2===null&&obj3===null&&obj4===null){document.getElementById('nav_subtabs').style.display="none";}else{document.getElementById('nav_subtabs').style.display="visible";$('.nav-pills li a[href="#'+tab+'"]').tab('show');}
if(tab=='readContract'){$('#readContract').attr('style','display:visible;');$('#writeContract').attr('style','display:none;');$('#readProxyContract').attr('style','display:none;');$('#writeProxyContract').attr('style','display:none;');}else if(tab=='writeContract'){$('#writeContract').attr('style','display:visible;');$('#readContract').attr('style','display:none;');$('#readProxyContract').attr('style','display:none;');$('#writeProxyContract').attr('style','display:none;');}else if(tab=='readProxyContract'){$('#writeContract').attr('style','display:none;');$('#readContract').attr('style','display:none;');$('#readProxyContract').attr('style','display:visible;');$('#writeProxyContract').attr('style','display:none;');}else if(tab=='writeProxyContract'){$('#writeContract').attr('style','display:none;');$('#readContract').attr('style','display:none;');$('#readProxyContract').attr('style','display:none;');$('#writeProxyContract').attr('style','display:visible;');}};};function removeHeight(){var element=document.getElementById('writecontractiframe');element.style.removeProperty("min-height");}
function updatehash(strhash){if(strhash==''){var baseUrl=window.location.href.split('#')[0];history.pushState("",document.title,baseUrl);}else{var baseUrl=window.location.href.split('#')[0];history.pushState("",document.title,baseUrl+'#'+strhash);};return true;}
var disqusloaded=false;function loaddisqus(){if(disqusloaded==false){var dsq=document.createElement('script');dsq.type='text/javascript';dsq.async=true;dsq.src='//'+disqus_shortname+'.disqus.com/embed.js';(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(dsq);disqusloaded=true;}
updatehash('comments');}
function showLoader(obj){if(obj==false){document.getElementById('overlayMain').style.display='block';}}
function loadIframeSource(){if(window.readContractLoaded==false){document.getElementById('overlayMain').style.display='block';document.getElementById('readcontractiframe').src='/readContract?m='+window.mode+'&a='+litreadContractAddress+'&v='+litContractABIAddressCode;}else{if(window.isBackButton==true&&window.isFrReadC==true){console.log("frame force reload");readcontractiframe.contentWindow.location.reload(true);window.isFrReadC=false;};};}
function loadIframeSource2(){if(window.token_holders_loaded==false){document.getElementById('overlayMain').style.display='block';document.getElementById('tokeholdersiframe').src='/token/generic-tokenholders2?m='+window.mode+'&a='+litTokenholdersContractUrlPara+'&sid='+sid+'&p=1';}else{if(window.isBackButton==true&&window.isFrHold==true){console.log("frame force reload");tokeholdersiframe.contentWindow.location.reload(true);window.isFrHold=false;};};}
function loadIframeSource3(){if(window.token_transactions_loaded==false){document.getElementById('overlayMain').style.display='block';document.getElementById('tokentxnsiframe').src='/token/generic-tokentxns2?m='+window.mode+'&contractAddress='+litContractAddress+'&a='+litAddress+'&sid='+sid+'&p=1';}else{if(window.isBackButton==true&&window.isFrTxns==true){console.log("frame force reload");tokentxnsiframe.contentWindow.location.reload(true);window.isFrTxns=false;};};}
function loadIframeSource5(){if(window.writeContractLoaded==false){document.getElementById('overlayMain').style.display='block';var src='/writecontract/index.html?m='+window.mode+'&v=21.10.1.1&a='+litwriteContractAddress+'&n='+clsvarschain;document.getElementById('writecontractiframe').src=src;}else{if(window.isBackButton==true&&window.isFrWriteC==true){console.log("frame force reload");writecontractiframe.contentWindow.location.reload(true);window.isFrWriteC=false;};};}
function loadIframeSource6(){if(window.token_inventory_loaded==false){document.getElementById('overlayMain').style.display='block';document.getElementById('tokenerc721_inventory_pageiframe').src='/token/generic-tokenholder-inventory?m='+window.mode+'&contractAddress='+litTokenContractAddress6+'&a='+litAddress6+'&pUrl=token';}else{if(window.isBackButton==true&&window.isFrInventory==true){console.log("frame force reload");tokenerc721_inventory_pageiframe.contentWindow.location.reload(true);window.isFrInventory=false;};};}
function loadIframeSource7(){if(window.dexTrackerLoaded==false){document.getElementById('overlayMain').style.display='block';var src='/dextracker_frame?m='+window.mode+'&q='+litDextrackerContractAddress+'&s='+litDextrackerSymbol+'&a='+litAddressdex;document.getElementById('dextrackeriframe').src=src;}else{if(window.isBackButton==true&&window.isFrDexTracker==true){console.log("frame force reload");dextrackeriframe.contentWindow.location.reload(true);window.isFrWriteC=false;};};}
function loadIframeSource8(){if(window.token_analytics_loaded==false){document.getElementById('overlayMain').style.display='block';document.getElementById('token_analytics_pageiframe').src='/token/token-analytics?m='+window.mode+'&contractAddress='+litTokenAnalyticsContractAddress+'&a='+litTokenAnalyticsAddress+'&lg='+litLanguage;}else{if(window.isBackButton==true&&window.isFrTokenAnayltics==true){console.log("frame force reload");token_analytics_pageiframe.contentWindow.location.reload(true);window.isFrTokenAnayltics=false;};};}
function loadIframeSourceProxyRead(){if(window.readProxyContractLoaded==false){window.readProxyContractLoaded=true;document.getElementById('readproxycontractiframe').src='/readContract?m='+window.mode+'&a='+litreadContractAddress+'&v='+litProxyContractABIAddress;}}
function loadIframeSourceProxyWrite(){if(window.writeProxyContractLoaded==false){window.writeProxyContractLoaded=true;document.getElementById('writeproxycontractiframe').src='/writecontract/index.html?m='+window.mode+'&v=21.10.1.1&a='+litreadContractAddress+'&p='+litProxyContractABIAddress+'&n='+strNetwork;}}
var blnIsCurrentPrice=true;var marketCapValue='0.00';var currentPrice='$0';var currentPriceValue='0';if(document.getElementById('pricebutton')!=null){currentPrice=document.getElementById('pricebutton').innerText;}
if(!String.prototype.startsWith){String.prototype.startsWith=function(searchString,position){position=position||0;return this.indexOf(searchString,position)===position;};}
if(litMarketCap.startsWith("$"))
marketCapValue=litMarketCap.substring(1);else
marketCapValue=litMarketCap.substring(4);if(currentPrice.startsWith("$"))
currentPriceValue=currentPrice.substring(1);else
currentPriceValue=currentPrice.substring(4);if(currentPriceValue==='0.00')currentPriceValue='0';if(marketCapValue=="0.00"&&currentPriceValue=="0"){$('#pricebutton').attr('data-original-title','Not available');}else if(litMarketCap=="0.00"&&currentPriceValue!="0"){$('#pricebutton').attr('data-original-title','Fully Diluted');}else if(currentPriceValue!="0"){var marketcaporititle=document.getElementById('marketcaptitle').innerHTML;$("#pricebutton").click(function(){if(blnIsCurrentPrice==true){document.getElementById('pricebutton').innerText=litMarketCap||"Not Available";$('#pricebutton').attr('data-original-title','Click to switch back');$('#pricebutton').tooltip('show');document.getElementById('marketcaptitle').innerText="Circulating Supply Market Cap";document.getElementById('marketcaptooltip').style.display="none";blnIsCurrentPrice=false;}else{document.getElementById('pricebutton').innerText=currentPrice;$('#pricebutton').attr('data-original-title','Click to switch');$('#pricebutton').tooltip('show');document.getElementById('marketcaptitle').innerHTML=marketcaporititle;document.getElementById('marketcaptooltip').style.display="";blnIsCurrentPrice=true;}
$(this).blur()});}else{$('#pricebutton').attr('data-original-title','Not Available');}
function resizeIframe(obj,addwidth){setTimeout(function(){obj.style.height=0;obj.style.height=(obj.contentWindow.document.body.scrollHeight+addwidth)+20+'px';obj.parentElement.style.visibility='visible';},300);}
function loadFancyBox(obj,index){$.fancybox.defaults.loop=true;$.fancybox.open(obj,{afterLoad:function(instance,current){if(current.width==0){current.width=400
current.height=400;}else if(current.width<200){current.width=current.width*3;current.height=current.height*3;}else{current.width=current.width*1.3;current.height=current.height*1.3;}
if(instance.currIndex===current.index){var tokenid=$(this.opts).attr("tokenid");var owner=$(this.opts).attr("owner");var contractaddress=$(this.opts).attr("contractaddress");if(tokenid){tokenid=litTokenID+" : #<a href='/token/"+contractaddress+"?a="+tokenid+"' target='_parent'>"+tokenid+"</a></span>"
$(".fancybox-tokenid").html(tokenid);}
if(owner){owner="<span class='d-block owner'>"+litOwner+": <a href='/token/"+contractaddress+"?a="+owner+"' target='_parent'>"+owner+"</a></span>"
$(".fancybox-owner").html(owner);}}},baseTpl:'<div class="fancybox-container" role="dialog" tabindex="-1">'+
'<div class="fancybox-bg"></div>'+
'<div class="fancybox-inner">'+
'<div class="fancybox-infobar"><span data-fancybox-index></span>&nbsp;/&nbsp;<span data-fancybox-count></span></div>'+
'<div class="fancybox-toolbar">{{buttons}}</div>'+
'<div class="fancybox-navigation">{{arrows}}</div>'+
'<div class="fancybox-stage"></div>'+
'<div class="fancybox-caption fancybox-caption--separate"><div class="fancybox-tokenid fancybox-caption__body"></div><div class="fancybox-owner fancybox-caption__body"></div></div>'+
"</div>"+
"</div>"},index);}
function addToWallet(){if(typeof ethereum!=='undefined'){web3obj=new Web3(ethereum);}else if(typeof web3!=='undefined'){web3obj=new Web3(web3.currentProvider);}else{alert('No web3 provider');return;}
var network=0;web3obj.eth.net.getId((err,netId)=>{network=netId.toString();switch(network){case "1":network='mainnet';break;case "2":network='morden';break;case "3":network='ropsten';break;case "4":network='rinkeby';break;case "5":network='goerli';break;case "42":network='kovan';break;case "246":network='ecw';break
default:console.log('This is an unknown network.');}
if(network.toLowerCase()!==net.toLowerCase()){alert("Please connect to "+net+' network');return false;}else{try{web3obj.eth.currentProvider.sendAsync({method:'wallet_watchAsset',params:{'type':litAssetType,'options':{'address':litAssetAddress,'symbol':litAssetSymbol,'decimals':litAssetDecimal,'image':litAssetLogo,},},id:Math.round(Math.random()*100000)},function(err,data){if(!err){if(data.result){console.log('Token added');}else{console.log(data);console.log('Some error');}}else{console.log(err.message);}});}catch(e){console.log(e);}}});}
$('.js-tab-external-link').on('click',function(event){event.preventDefault();$('[data-toggle="tab"][href="'+this.hash+'"]').trigger('click');});function goToContactUs(){window.location.href='/contactus?id=4';}
function renderSupplyBurnt(){$("#divSupplyBurnt").text("");$.ajax({dataType:"json",type:'GET',url:'/renderDynamicTooltip.ashx',data:{term:"getsuppyburnt"+"~"+litContAdd},success:function(data){$("#spinwheel").prop("style","display:none;");var i;var flag=false;var strContent;var totalBurnt=0;strContent="<ul class='list-unstyled my-3'>";for(i=0;i<data.length;i++){if(data[i].split('\t')[1]!=""){flag=true;var j=i+1;strContent=strContent+"<li class='row mb-3'><div class='col-7'><div class='media'><div class='btn btn-xs btn-icon btn-soft-secondary rounded-circle mr-2'><span class='btn-icon__inner'>"+j+"</span></div>"
var link="";if(data[i].split('\t')[2]!=""){link="<a href='"+data[i].split('\t')[2]+"' target='_blank' class='link-hover-secondary' rel='nofollow'><i class='far fa-external-link-alt ml-1'></i></a>";}
strContent=strContent+"<div class='media-body'>"+data[i].split('\t')[1]+link+" ";var txn=""
if(data[i].split('\t')[3]!=""){txn="<span class='d-block text-secondary text-nowrap'>Txn: <a href='/tx/"+data[i].split('\t')[3]+"' target='_blank' class='hash-tag hash-tag--xss text-truncate'>"+data[i].split('\t')[3]+"</a>"+data[i].split('\t')[4]+"</span>";}
var burntVal=data[i].split('\t')[5].toString().split(".");strContent=strContent+txn+"</div></div></div><div class='col text-right'>-"+burntVal[0]+"."+burntVal[1].slice(0,8)+"... "+$("#ContentPlaceHolder1_hdnSymbol").val()+"</div></li>";totalBurnt=parseFloat(totalBurnt)+parseFloat(data[i].split('\t')[5]);}}
if(flag===true){var total="<li><hr class='my-3'></li><li class='row mb-1'><div class='col-5'>Total Burn:</div><div class='col text-right'><strong>-"+totalBurnt.toFixed(18)+" "+$("#ContentPlaceHolder1_hdnSymbol").val()+"</strong></div></li>";var actualValue=(parseFloat($("#ContentPlaceHolder1_hdnTotalSupply").val().replace(/,/g,''))-totalBurnt).toFixed(18);var array=actualValue.toString().split(".");var afterBurn="<li class='row'><div class='col-5'>Total Supply (After Burn):</div><div class='col text-right'><strong>"+array[0].toString().replace(/\B(?=(\d{3})+(?!\d))/g,",")+"."+array[1]+"</span> "+$("#ContentPlaceHolder1_hdnSymbol").val()+"</strong></div></li>";strContent=strContent+total+afterBurn+"</ul>";$("#divSupplyBurnt").append(strContent);}
else{$("#divSupplyBurnt").append("<div class='u-label--warning text-center'>No data.</div>");}},error:function(XMLHttpRequest,textStatus,errorThrown){console.log(textStatus);console.log(errorThrown);}});}
$('#infoSupplyBurnt').popover({trigger:"click",html:true,content:"<div id='divSupplyBurnt'><i id='spinwheel' class='fa fa-spin fa-spinner fa-1x fa-pulse mr-1' style='display: block;'></i></div>",title:"Token Burn Events"});$('body').on('click',function(e){if($(e.target).data('toggle')!=='popover'&&$(e.target).parents('.popover.in').length===0){$('[data-toggle="popover"]').popover('hide');}});if(blnCheckDisqusCount==true){checkdisquscomment();}
function checkdisquscomment(){$.ajax({type:'Get',url:'/datahandler.ashx',data:{t:'disqcommentchck',id:disqus_title,type:'tkn'},success:function(res){if(res==1){document.getElementById("commentindicator").innerHTML="<sup><i class='fas fa-circle text-success ml-1' title='There are comment(s) for this item'></i></sup>"}},error:function(XMLHttpRequest,textStatus,errorThrown){}});}
if(holdersplotData!=''){var sparkOptions={chart:{renderTo:'sparkholderscontainer',backgroundColor:null,borderWidth:0,type:'area',margin:[2,0,2,0],width:120,height:20,style:{overflow:'visible'},skipClone:true},title:{text:''},credits:{enabled:false},xAxis:{labels:{enabled:false},title:{text:null},startOnTick:false,endOnTick:false,tickPositions:[]},yAxis:{min:holdersplotMinValue,endOnTick:false,startOnTick:false,labels:{enabled:false},title:{text:null},tickPositions:[0]},legend:{enabled:false},tooltip:{hideDelay:0,outside:true,shared:true,formatter:function(){var content="";if(blnAlsoShowPriceInSpark==true){$.each(this.points,function(i,point){content+='<span style="font-size: 11px">'+Highcharts.dateFormat('%a %e, %b %Y',new Date(this.x))
+'<br><b>'+this.y+'</b> Holders</span>'+'<br><br>('+this.point.cval+')';});}else{content='<span style="font-size: 11px">'+Highcharts.dateFormat('%a %e, %b %Y',new Date(this.x))
+'<br><b>'+this.y+'</b> Holders</span>';}
return content;}},plotOptions:{series:{animation:false,lineWidth:1,shadow:false,states:{hover:{lineWidth:1}},marker:{radius:1,states:{hover:{radius:2}}},fillOpacity:0.25},column:{negativeColor:'#910000',borderColor:'silver'}}};var t=new Highcharts.Chart(sparkOptions);t.addSeries({keys:['x','y'],data:holdersplotData});}